export const cardList = [
  {
    id: 1,
    theme: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
    color: "orange",
  },
  {
    id: 2,
    theme: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
    color: "green",
  },
  {
    id: 3,
    theme: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
    color: "orange",
  },
  {
    id: 4,
    theme: "Copywriting",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
    color: "purple",
  },
  {
    id: 5,
    theme: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
    color: "orange",
  },
  {
    id: 6,
    theme: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "Нужно сделать",
    color: "green",
  },
  {
    id: 7,
    theme: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "В работе",
    color: "green",
  },
  {
    id: 8,
    theme: "Copywriting",
    title: "Название задачи",
    date: "30.10.23",
    status: "В работе",
    color: "purple",
  },
  {
    id: 9,
    theme: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    status: "В работе",
    color: "orange",
  },
  {
    id: 10,
    theme: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "Тестирование",
    color: "green",
  },
  {
    id: 11,
    theme: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "Готово",
    color: "green",
  },
]; 
