// export const cardList = [
//   {
//     id: 1,
//     topic: "Web Design",
//     title: "Название задачи",
//     // description: "Введите описание задачи...",
//     date: "30.10.23",
//     status: "Без статуса",
//     color: "orange",
//   },
//   {
//     id: 2, 
//     topic: "Research",
//     title: "Название задачи",
//     // description: "Описание",
//     date: "30.10.23",
//     status: "Без статуса",
//     color: "green",
//   },
//   {
//     id: 3,
//     topic: "Web Design",
//     title: "Название задачи",
//     // description: "Описание",
//     date: "30.10.23",
//     status: "Без статуса",
//     color: "orange",
//   },
//   {
//     id: 4,
//     topic: "Copywriting",
//     title: "Название задачи",
//     // description: "Описание",
//     date: "30.10.23",
//     status: "Без статуса",
//     color: "purple",
//   },
//   {
//     id: 5,
//     topic: "Web Design",
//     title: "Название задачи",
//     // description: "Описание",
//     date: "30.10.23",
//     status: "Без статуса",
//     color: "orange",
//   },
//   {
//     id: 6,
//     topic: "Research",
//     title: "Название задачи",
//     // description: "Описание",
//     date: "30.10.23",
//     status: "Нужно сделать",
//     color: "green",
//   },
//   {
//     id: 7,
//     topic: "Research",
//     title: "Название задачи",
//     // description: "Описание",
//     date: "30.10.23",
//     status: "В работе",
//     color: "green",
//   },
//   {
//     id: 8,
//     topic: "Copywriting",
//     title: "Название задачи",
//     // description: "Описание",
//     date: "30.10.23",
//     status: "В работе",
//     color: "purple",
//   },
//   {
//     id: 9,
//     topic: "Web Design",
//     title: "Название задачи",
//     // description: "Описание",
//     date: "30.10.23",
//     status: "В работе",
//     color: "orange",
//   },
//   {
//     id: 10,
//     topic: "Research",
//     title: "Название задачи",
//     // description: "Описание",
//     date: "30.10.23",
//     status: "Тестирование",
//     color: "green",
//   },
//   {
//     id: 11,
//     topic: "Research",
//     title: "Название задачи",
//     // description: "Описание",
//     date: "30.10.23",
//     status: "Готово",
//     color: "green",
//   },
// ]; 
